export const tools = [
  {
    id: "research",
    name: "Research Agent",
    group: "Assistant",
    icon: "Orbit",
    description: "Read the evidence. Build a grounded perspective.",
    field: "topic",
    label: "Research topic",
    placeholder: "What do you want to understand?",
    urls: 5,
    key: true,
    model: "gpt-4o-mini",
    steps: ["Plan", "Read", "Synthesize", "Review"],
  },
  {
    id: "documents",
    name: "Document Intelligence",
    group: "Assistant",
    icon: "ScanText",
    description: "Turn documents into decisions and action items.",
    files: ".pdf,.docx,.txt,.png,.jpg,.jpeg",
    maxFiles: 3,
    key: true,
    model: "gpt-4o-mini",
    steps: ["Extract", "Classify", "Analyze"],
  },
  {
    id: "document-qa",
    name: "Document Q&A",
    group: "Assistant",
    icon: "Files",
    description: "Ask your documents. Inspect the retrieved context.",
    files: ".pdf,.docx",
    maxFiles: 3,
    field: "question",
    label: "Your question",
    placeholder: "What do these documents tell us?",
    key: true,
    model: "gpt-4o-mini",
    steps: ["Index", "Retrieve", "Answer"],
  },
  {
    id: "url-qa",
    name: "Article Q&A",
    group: "Assistant",
    icon: "Link",
    description: "Find answers within your selected articles.",
    urls: 3,
    field: "question",
    label: "Your question",
    placeholder: "Ask a question about your sources",
    key: true,
    model: "gpt-4o-mini",
    steps: ["Index", "Retrieve", "Answer"],
  },
  {
    id: "support",
    name: "Support / Triage",
    group: "Assistant",
    icon: "LifeBuoy",
    description: "A sourced answer, or a clear path to human review.",
    field: "question",
    label: "Support question",
    placeholder: "Describe the issue to resolve",
    urls: 5,
    key: true,
    model: "gpt-4o-mini",
    steps: ["Classify", "Read", "Draft", "Decide"],
  },
  {
    id: "text-summary",
    name: "Text Summary",
    group: "Summarizer",
    icon: "AlignLeft",
    description: "Bring the important details into focus.",
    field: "text",
    label: "Source text",
    placeholder: "Paste the text to summarize",
    key: false,
    model: "Local distilbart / gpt-3.5-turbo",
    steps: ["Summarize"],
  },
  {
    id: "youtube-summary",
    name: "YouTube Summary",
    group: "Summarizer",
    icon: "Youtube",
    description: "Extract a transcript and distill the essentials.",
    field: "url",
    label: "YouTube URL",
    placeholder: "https://www.youtube.com/watch?v=…",
    key: false,
    model: "Local distilbart",
    steps: ["Extract", "Summarize"],
  },
  {
    id: "article-summary",
    name: "Article Summary",
    group: "Summarizer",
    icon: "Newspaper",
    description: "A readable summary of a public article.",
    field: "url",
    label: "Article URL",
    placeholder: "https://…",
    key: false,
    model: "Local distilbart",
    steps: ["Extract", "Summarize"],
  },
  {
    id: "file-summary",
    name: "File Summary",
    group: "Summarizer",
    icon: "FileText",
    description: "Less time reading. More time understanding.",
    files: ".pdf,.docx",
    maxFiles: 1,
    key: false,
    model: "Local distilbart",
    steps: ["Extract", "Summarize"],
  },
  {
    id: "ocr",
    name: "Image to Text",
    group: "Summarizer",
    icon: "ScanLine",
    description: "Lift text from an image. Summarize it when ready.",
    files: ".png,.jpg,.jpeg",
    maxFiles: 1,
    key: false,
    model: "Tesseract OCR",
    steps: ["Extract"],
  },
  {
    id: "image",
    name: "Image Studio",
    group: "Generator",
    icon: "Image",
    description: "Describe a visual. Give it a frame.",
    field: "prompt",
    label: "Image prompt",
    placeholder: "Describe your scene, composition, lighting and style",
    key: true,
    model: "gpt-image-1",
    steps: ["Generate"],
  },
  {
    id: "speech",
    name: "Speech Studio",
    group: "Generator",
    icon: "AudioLines",
    description: "Give your words a voice.",
    field: "text",
    label: "Narration text",
    placeholder: "Write the text to speak",
    voice: true,
    key: true,
    model: "tts-1",
    steps: ["Generate"],
  },
  {
    id: "captions",
    name: "YouTube Captions",
    group: "Generator",
    icon: "Captions",
    description: "Your transcript, ready to read and copy.",
    field: "url",
    label: "YouTube URL",
    placeholder: "https://www.youtube.com/watch?v=…",
    key: true,
    model: "YouTube transcript extraction",
    steps: ["Extract"],
  },
  {
    id: "code",
    name: "Code Copilot",
    group: "Generator",
    icon: "SquareCode",
    description: "Generate. Check. Repair once when needed.",
    field: "prompt",
    label: "Code task",
    placeholder: "Describe the function, inputs and expected behavior",
    key: true,
    model: "gpt-4o-mini",
    steps: ["Generate", "Verify", "Repair if needed"],
  },
  {
    id: "content",
    name: "Content Pipeline",
    group: "Generator",
    icon: "Layers",
    description: "One idea. A coherent set of creative artifacts.",
    field: "idea",
    label: "Content idea",
    placeholder: "What are you creating, and who is it for?",
    voice: true,
    key: true,
    model: "gpt-4o-mini · optional tts-1",
    steps: ["Plan", "Create", "Review", "Narrate if selected"],
  },
] as const;
export type ToolId = (typeof tools)[number]["id"];
export type Tool = {
  id: ToolId;
  name: string;
  group: string;
  icon: string;
  description: string;
  field?: string;
  label?: string;
  placeholder?: string;
  urls?: number;
  files?: string;
  maxFiles?: number;
  voice?: boolean;
  key: boolean;
  model: string;
  steps: readonly string[];
};
export const groups = ["Summarizer", "Generator", "Assistant"];
export const voices = ["alloy", "echo", "fable", "onyx", "nova", "shimmer"];
export const platforms = ["linkedin", "x", "instagram", "youtube", "blog"];
export const tones = [
  "professional",
  "playful",
  "educational",
  "launch-ready",
  "social-first",
];
export const featured: ToolId[] = [
  "research",
  "documents",
  "code",
  "content",
  "support",
];
export const github = "https://github.com/Archit-k20/Agentic-Workflows-GenAI-";
export const linkedin = "https://www.linkedin.com/in/archit-kumar-aa6375259";
